name: Security Policy Guard Test
description: Check if there are any HTTPRoutes without security policies
author: francis-padua

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: green

inputs:
  github-token:
    description: GitHub token to use for API requests
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

# Define your outputs here.
outputs:
  unmatched_routes:
    description: List of HTTPRoutes without security policies

runs:
  using: node24
  main: dist/index.js
