name: Security Policy Guard Test
description: Check if there are any HTTPRoutes without security policies
author: francis-padua

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: green

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node24
  main: dist/index.js
